heislab: elev_test.c File Reference
elev_test.c File Reference
#include "elevio.h"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 3 of file elev_test.c.
              {
    elevio_init();
    while(1){
        elevio_motorDirection(DIRN_DOWN);
        while(elevio_floorSensor() != 0){}
        elevio_motorDirection(DIRN_UP);
        while(elevio_floorSensor() != 3){}
    }
}
References DIRN_DOWN, DIRN_UP, elevio_floorSensor(), elevio_init(), and elevio_motorDirection().