heislab: main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <time.h>
#include "driver/elevio.h"
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 9 of file main.c.
          {
    elevio_init();
    printf("=== Example Program ===\n");
    printf("Press the stop button on the elevator panel to exit\n");
    elevio_motorDirection(DIRN_UP);
    while(1){
        int floor = elevio_floorSensor();
        if(floor == 0){
            elevio_motorDirection(DIRN_UP);
        }
        if(floor == N_FLOORS-1){
            elevio_motorDirection(DIRN_DOWN);
        }
        for(int f = 0; f < N_FLOORS; f++){
            for(int b = 0; b < N_BUTTONS; b++){
                int btnPressed = elevio_callButton(f, b);
                elevio_buttonLamp(f, b, btnPressed);
            }
        }
        if(elevio_obstruction()){
            elevio_stopLamp(1);
        } else {
            elevio_stopLamp(0);
        }
        if(elevio_stopButton()){
            elevio_motorDirection(DIRN_STOP);
            break;
        }
        nanosleep(&(struct timespec){0, 20*1000*1000}, NULL);
    }
    return 0;
}
References DIRN_DOWN, DIRN_STOP, DIRN_UP, elevio_buttonLamp(), elevio_callButton(), elevio_floorSensor(), elevio_init(), elevio_motorDirection(), elevio_obstruction(), elevio_stopButton(), elevio_stopLamp(), N_BUTTONS, and N_FLOORS.